# Use container-based infrastructure
sudo: required
dist: trusty

matrix:
  include:
    - language: node_js
      node_js:
        - 8
      cache:
        directories:
          - node_modules
      script:
        - npm install
        - npm run test:cov
      after_success:
        - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js

branches:
  only:
  - master
  - travis-ci
